server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<path>.*), /posts/$\{path}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
          filters:
            - RewritePath=/reviews/(?<path>.*), /reviews/$\{path}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
          filters:
            - RewritePath=/comments/(?<path>.*), /comments/$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/